/**
 * Cookie Manager
 * 
 * Handles cookie storage and retrieval in Netscape Cookie Jar format.
 */

import fs from 'fs';
import { extractCookies, parseCookie } from '../http/response.js';

/**
 * Save cookies to file (Netscape Cookie Jar format)
 * @param {string[]} cookies - Array of Set-Cookie values
 * @param {string} filePath - Output file path
 * @param {string} defaultDomain - Default domain for cookies without domain
 * @returns {number} - Number of cookies saved
 */
export function saveCookies(cookies, filePath, defaultDomain = '') {
    let content = '# Netscape HTTP Cookie File\n';
    content += '# Generated by jsurl\n';
    content += `# Date: ${new Date().toISOString()}\n\n`;
    
    for (const cookieStr of cookies) {
        const cookie = parseCookie(cookieStr);
        
        const domain = cookie.domain || defaultDomain;
        const tailmatch = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const secure = cookie.secure ? 'TRUE' : 'FALSE';
        
        let expires = '0';
        if (cookie.expires) {
            expires = Math.floor(cookie.expires.getTime() / 1000).toString();
        } else if (cookie.maxAge) {
            expires = (Math.floor(Date.now() / 1000) + cookie.maxAge).toString();
        }
        
        // Format: domain, tailmatch, path, secure, expires, name, value
        content += `${domain}\t${tailmatch}\t${cookie.path}\t${secure}\t${expires}\t${cookie.name}\t${cookie.value}\n`;
    }
    
    fs.writeFileSync(filePath, content);
    return cookies.length;
}

/**
 * Load cookies from file (Netscape Cookie Jar format)
 * @param {string} filePath - Input file path
 * @returns {string} - Cookie header value
 */
export function loadCookies(filePath) {
    if (!fs.existsSync(filePath)) {
        return '';
    }
    
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');
    const cookies = [];
    
    for (const line of lines) {
        // Skip comments and empty lines
        if (line.startsWith('#') || line.trim() === '') {
            continue;
        }
        
        const parts = line.split('\t');
        if (parts.length >= 7) {
            const name = parts[5];
            const value = parts[6];
            cookies.push(`${name}=${value}`);
        }
    }
    
    return cookies.join('; ');
}

/**
 * Process response cookies and save if needed
 * @param {string} response - Raw HTTP response
 * @param {string} cookieJar - Cookie jar file path (optional)
 * @param {string} host - Default domain
 * @returns {{ cookies: string[], saved: number }}
 */
export function processResponseCookies(response, cookieJar, host) {
    const cookies = extractCookies(response);
    let saved = 0;
    
    if (cookies.length > 0 && cookieJar) {
        saved = saveCookies(cookies, cookieJar, host);
    }
    
    return { cookies, saved };
}
